pipeline {
    agent { label 'aws-agent' }

    stages {
        stage('Checkout Source') {
            steps {
                checkout scm
            }
        }

        stage('Setup AWS Credentials') {
            steps {
                // 'aws-creds' is the ID of your credentials in Jenkins
                withCredentials([usernamePassword(credentialsId: 'aws-creds', 
                                 passwordVariable: 'AWS_SECRET_ACCESS_KEY', 
                                 usernameVariable: 'AWS_ACCESS_KEY_ID')]) {
                    
                    // Setting a default region is required for Terraform/AWS CLI
                    sh 'aws configure set region ap-southeast-1'
                    
                    echo "AWS Credentials and region configured."
                    
                    // Verify connectivity
                    sh 'aws sts get-caller-identity'
                }
            }
        }

        stage('Version Check') {
            steps {
                sh '''
                    kubectl version --client
                    eksctl version
                    terraform version
                '''
            }
        }

        stage('Terraform Init & Plan') {
            steps {
                // Since Jenkinsfile is inside 'vpc', we enter that directory
                dir('vpc') {
                    sh 'terraform init'
                    sh 'terraform plan -out=tfplan'
                }
            }
        }
    }

    post {
        success {
            sh 'kubectl get nodes'
        }
    }
}
